### ISSUE TITLE
Undefined symbol in wit.so: CRYPTO_memcmp

### ISSUE THREAD

**Issue by sciguy14** [wit-ai/pywit#4]
HI! I was able to install the python wit library on my UDOO Quad board (http://shop.udoo.org/usa/product/udoo-quad.html). However, when I try to import the wit library, I get this error:
`Traceback (most recent call last):
File "<stdin>", line 1, in <module>
ImportError: /usr/local/lib/python2.7/dist-packages/wit.so: undefined symbol: CRYPTO_memcmp`

Any thoughts on why?

**Comment by sciguy14** [comment]
Hey folks, any update on this? I still can't run wit from python  on an armv7 :(

**Comment by sciguy14** [comment]
It's been almost a year. Think this will get resolved at some point?

**Comment by blandinw** [comment]
@sciguy14 Unfortunately, we don't have the bandwidth to work on this issue at the moment.
We'll gladly accept a pull request if you find the time to look at it.

**Comment by blandinw** [comment]
We moved away from audio recording and streaming because:
- many people only needed access to the HTTP API, and audio recording did not make sense for server-side use cases
- dependent on platform, choice best left to developers
- forced us to maintain native bindings as opposed to a pure Pythonic library
